apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: weekly-most-starred-job
    environment: prod
    app.kubernetes.io/name: crossd
    app.kubernetes.io/instance: crossd-alpha
    app.kubernetes.io/version: "0.1"
    app.kubernetes.io/component: weekly-most-starred-job
    app.kubernetes.io/part-of: crossd
  name: weekly-most-starred-job
spec:
  schedule: "45 19 * * 1"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: weekly-most-starred-job
            image: localhost:32000/add-task
            command: ["sh" , "-c"]
            args:
            - >
              python3 add_task.py --user $USER --password $PASSWORD -t most-starred-09-04-2024 -t $(date -uI)
              $(cat /most-starred-repos.txt)
            env:
            - name: REQUESTS_CA_BUNDLE
              value: /etc/ssl/certs/ca-certificates.crt
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: arango-worker-pwd
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: arango-worker-pwd
                  key: password
            - name: RAUTH
              valueFrom:
                secretKeyRef:
                  name: redis-auth
                  key: RAUTH
            volumeMounts:
            - name: ca-certificates
              mountPath: /etc/ssl/certs/
              readOnly: true
            - name: "most-starred-repos"
              mountPath: "/most-starred-repos.txt"
              subPath: "starred_repos.txt"
          restartPolicy: Never
          volumes:
          - name: ca-certificates
            configMap:
              name: cert-bundle
              defaultMode: 0644
              optional: false
              items:
              - key: ca-certificates.crt
                path: ca-certificates.crt
          - name: "most-starred-repos"
            configMap:
              name: "most-starred-repos"
      backoffLimit: 4