apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: c-drone
    environment: prod
    app.kubernetes.io/name: crossd
    app.kubernetes.io/instance: crossd-alpha
    app.kubernetes.io/version: "0.1"
    # app.kubernetes.io/managed-by: helm
    app.kubernetes.io/component: c-drone
    app.kubernetes.io/part-of: crossd
  name: c-drone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: c-drone
  strategy: {type: RollingUpdate}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: c-drone
        pod: c-drone
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 1337
        runAsGroup: 1337
      containers:
      - image: localhost:32000/worker-drone
        # args:
        #     - sh
        #     - -c
        #     - ' docker-entrypoint.sh --appendonly "yes" '
        # ports:
        # - containerPort: 6379
        imagePullPolicy: Always
        name: c-drone
        args: ["-Q", "collect", "-c", "1"]
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: GH_TOKEN
          valueFrom:
            secretKeyRef:
              name: ghtoken
              key: GH_TOKEN
        volumeMounts:
        # name must match the volume name below
        - name: secret-volume
          mountPath: /home/collector-drone/.env
          readOnly: true
        # volumeMounts:
        #     - mountPath: /data
        #       name: redis-pvc
              # readOnly: true
      # volumes:
      #   - name: redis-pvc
      #     persistentVolumeClaim:
      #       claimName: redis-pvc
            # readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: ghtoken
status: {}
