apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flower
    environment: prod
    app.kubernetes.io/name: crossd
    app.kubernetes.io/instance: crossd-alpha
    app.kubernetes.io/version: "0.1"
    app.kubernetes.io/component: flower
    app.kubernetes.io/part-of: crossd
  annotations:
    reloader.stakater.com/auto: "true"
  name: flower
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: flower
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flower
        pod: flower
    spec:
      containers:
        - name: flower
          image: mher/flower
          ports:
            - containerPort: 5555
          command: ["sh", "-c"]
          args:
            - "celery --broker=redis://:$RAUTH@redis-service:6379/0?ssl_cert_reqs=required flower"
          imagePullPolicy: Always
          env:
            - name: REQUESTS_CA_BUNDLE
              value: /etc/ssl/certs/ca-certificates.crt
            - name: FLOWER_BASIC_AUTH
              valueFrom:
                secretKeyRef:
                  name: flower-basic-auth
                  key: AUTH
            - name: RAUTH
              valueFrom:
                secretKeyRef:
                  name: redis-auth
                  key: RAUTH
          volumeMounts:
            - name: ca-certificates
              mountPath: /etc/ssl/certs/
              readOnly: true
      volumes:
        - name: ca-certificates
          configMap:
            name: cert-bundle
            defaultMode: 0644
            optional: false
            items:
              - key: ca-certificates.crt
                path: ca-certificates.crt
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
