kind: Service
apiVersion: v1
metadata:
  name: frontend-service
spec:
  selector:
    pod: frontend
  type: NodePort
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30380
