apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend
    environment: prod
    app.kubernetes.io/name: crossd
    app.kubernetes.io/instance: crossd-alpha
    app.kubernetes.io/version: "0.1"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: crossd
  annotations:
    reloader.stakater.com/auto: "true"
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: { type: RollingUpdate }
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
        pod: frontend
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 1337
        runAsGroup: 1337
      containers:
        - image: localhost:32000/frontend
          imagePullPolicy: Always
          name: frontend
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          env:
            - name: NODE_OPTIONS
              value: --use-openssl-ca
            - name: NODE_ENV
              value: "production"
            - name: FRONTEND_USER
              valueFrom:
                secretKeyRef:
                  name: arango-frontend-pwd
                  key: username
            - name: FRONTEND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: arango-frontend-pwd
                  key: password
            - name: ARANGO_URL
              value: "https://arangodb-cluster-internal:8529"
            - name: ORIGIN
              value: http://172.23.101.111:30380
          volumeMounts:
            - name: ca-certificates
              mountPath: /etc/ssl/certs/
              readOnly: true
      volumes:
        - name: ca-certificates
          configMap:
            name: cert-bundle
            defaultMode: 0644
            optional: false
            items:
              - key: ca-certificates.crt
                path: ca-certificates.crt
status: {}
