apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: m-drone
    environment: prod
    app.kubernetes.io/name: crossd
    app.kubernetes.io/instance: crossd-alpha
    app.kubernetes.io/version: "0.1"
    # app.kubernetes.io/managed-by: helm
    app.kubernetes.io/component: m-drone
    app.kubernetes.io/part-of: crossd
  name: m-drone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m-drone
  strategy: {type: RollingUpdate}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: m-drone
        pod: m-drone
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 1337
        runAsGroup: 1337
      containers:
      - image: localhost:32000/worker-drone
        # args:
        #     - sh
        #     - -c
        #     - ' docker-entrypoint.sh --appendonly "yes" '
        # ports:
        # - containerPort: 6379
        imagePullPolicy: Always
        name: m-drone
        args: ["-Q", "metric", "-c", "1"]
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        env:
        - name: REQUESTS_CA_BUNDLE
          value: /etc/ssl/certs/ca-certificates.crt
        - name: PDM_LOG_DIR
          value: /tmp
        - name: GH_TOKEN
          valueFrom:
            secretKeyRef:
              name: ghtoken
              key: GH_TOKEN
        - name: WORKER_USER
          valueFrom:
            secretKeyRef:
              name: arango-worker-pwd
              key: username
        - name: WORKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: arango-worker-pwd
              key: password
        - name: PYTHONUNBUFFERED
          value: "1"
        volumeMounts:
        - name: ca-certificates
          mountPath: /etc/ssl/certs/
          readOnly: true
        - name: tmp
          mountPath: /tmp
        # name must match the volume name below
        # - name: secret-volume
        #   mountPath: /home/m-drone/.env
        #   readOnly: true
        # volumeMounts:
        #     - mountPath: /data
        #       name: redis-pvc
              # readOnly: true
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 500Mi
        - name: ca-certificates
          configMap:
            name: cert-bundle
            defaultMode: 0644
            optional: false
            items:
            - key: ca-certificates.crt
              path: ca-certificates.crt
      #   - name: redis-pvc
      #     persistentVolumeClaim:
      #       claimName: redis-pvc
            # readOnly: true
      # volumes:
      # - name: secret-volume
      #   secret:
      #     secretName: ghtoken
status: {}
