apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  # labels:
  #   io.kompose.service: interface-basic-auth-claim0
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
# status: {}
