apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: update-arango-ca-role
rules:
  - apiGroups: [""]
    resources:
      - secrets
    resourceNames:
      - root-secret
    verbs:
      - get
  - apiGroups: [""]
    resources:
      - secrets
    resourceNames:
      - arango-ca
    verbs:
      - patch
      - get
