apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: update-arango-ca-rb
subjects:
  - kind: ServiceAccount
    name: update-arango-ca-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: update-arango-ca-role
  apiGroup: rbac.authorization.k8s.io
