apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: cert-bundle
spec:
  sources:
  - useDefaultCAs: true
  - secret:
      name: "root-secret"
      key: "ca.crt"
  target:
    configMap:
      key: "ca-certificates.crt"