apiVersion: v1
kind: Service
metadata:
  name: {{ include "arcadedb.fullname" . }}-https-external
  labels:
    {{- include "arcadedb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.https.type }}
  ports:
    - port: {{ .Values.service.https.port }}
      targetPort: https
      protocol: TCP
      name: https
    # - port : 6379
    #   targetPort: redis
    #   protocol: TCP
    #   name: redis
  selector:
    {{- include "arcadedb.selectorLabels" . | nindent 4 }}

---

{{/*
This is a "headless" service for the arcadedb which exists to allow discovery of the set of
member pods (masters). The CNAME of this service points to SRV records - one for each Pod that
is Running and Ready). Read more in the Kubernetes docs:
https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/
*/}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "arcadedb.fullname" . }}-https
  labels:
    {{- include "arcadedb.labels" . | nindent 4 }}
spec:
  # clusterIP: None
  type: ClusterIP
  ports:
    - port: {{ .Values.service.https.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "arcadedb.selectorLabels" . | nindent 4 }}
