apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: add-comment-job
    environment: prod
    app.kubernetes.io/name: crossd
    app.kubernetes.io/instance: crossd-alpha
    app.kubernetes.io/version: "0.1"
    app.kubernetes.io/component: add-comment-job
    app.kubernetes.io/part-of: crossd
  name: add-comment-job
spec:
  template:
    spec:
      containers:
        - name: add-comment-job
          image: ghcr.io/fh-crossd/add-task:latest
          #image: localhost:32000/add-task:latest
          command: ["sh", "-c"]
          args:
            - >
              python3 add_task.py --user $USER --password $PASSWORD -t manual --queue comments
              lorabridge/lorabridge
              #golang/go
              #microsoft/vscode
              #Ebazhanov/linkedin-skill-assessments-quizzes
              #Make-O-Matic/MOM-Base 
          env:
            - name: REQUESTS_CA_BUNDLE
              value: /etc/ssl/certs/ca-certificates.crt
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: arango-worker-pwd
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: arango-worker-pwd
                  key: password
            - name: RAUTH
              valueFrom:
                secretKeyRef:
                  name: redis-auth
                  key: RAUTH
          volumeMounts:
            - name: ca-certificates
              mountPath: /etc/ssl/certs/
              readOnly: true
      restartPolicy: Never
      volumes:
        - name: ca-certificates
          configMap:
            name: cert-bundle
            defaultMode: 0644
            optional: false
            items:
              - key: ca-certificates.crt
                path: ca-certificates.crt
  backoffLimit: 4
