apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: random-sample-job
    environment: prod
    app.kubernetes.io/name: crossd
    app.kubernetes.io/instance: crossd-alpha
    app.kubernetes.io/version: "0.1"
    app.kubernetes.io/component: random-sample-job
    app.kubernetes.io/part-of: crossd
  name: random-sample-job
spec:
  template:
    spec:
      containers:
        - name: random-sample-job
          image: ghcr.io/fh-crossd/add-task:latest
          command: ["sh", "-c"]
          args:
            - >
              python3 add_task.py --user $USER --password $PASSWORD -t random-sample-09-04-2024
              $(cat /random-sample-repos.txt)
          env:
            - name: REQUESTS_CA_BUNDLE
              value: /etc/ssl/certs/ca-certificates.crt
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: arango-worker-pwd
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: arango-worker-pwd
                  key: password
            - name: RAUTH
              valueFrom:
                secretKeyRef:
                  name: redis-auth
                  key: RAUTH
          volumeMounts:
            - name: ca-certificates
              mountPath: /etc/ssl/certs/
              readOnly: true
            - name: "random-sample-repos"
              mountPath: "/random-sample-repos.txt"
              subPath: "random_samples_filtered.txt"
      restartPolicy: Never
      volumes:
        - name: ca-certificates
          configMap:
            name: cert-bundle
            defaultMode: 0644
            optional: false
            items:
              - key: ca-certificates.crt
                path: ca-certificates.crt
        - name: "random-sample-repos"
          configMap:
            name: "random-sample-repos"
  backoffLimit: 4
