apiVersion: v2
name: arcadedb
description: |
  A Helm chart for ArcadeDB

type: application

version: 26.4.2

appVersion: "26.4.2"
annotations:
  artifacthub.io/repositoryID: "fb85acb7-fb5b-4572-b44b-374a2b52658d"
