apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: arango-storage-configmaps-role
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    verbs:
      - create
      - get
